name: release

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasi

      - name: build WASM file
        run: cargo build --release --target wasm32-wasi

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          tag: latest
          artifacts: target/wasm32-wasi/release/merge-headers.wasm
          token: ${{ secrets.GITHUB_TOKEN }}
